export const segments = [
    { id: 1, text: "1000 XPOINTS", color: "bg-red" },
    { id: 2, text: "NONE", color: "bg-black" },
    { id: 3, text: "5 USDT", color: "bg-blue" },
    { id: 4, text: "NONE", color: "bg-black" },
    { id: 5, text: "NONE", color: "bg-black" },
    { id: 6, text: "5 USDT", color: "bg-blue" },
    { id: 7, text: "NONE", color: "bg-black" },
    { id: 8, text: "5 XTICKET", color: "bg-purple" },
    { id: 9, text: "NONE", color: "bg-black" },
    { id: 10, text: "NONE", color: "bg-black" },
    { id: 11, text: "1000 XPOINTS", color: "bg-red" },
    { id: 12, text: "NONE", color: "bg-black" },
    { id: 13, text: "NONE", color: "bg-black" },
    { id: 14, text: "5 USDT", color: "bg-blue" },
    { id: 15, text: "NONE", color: "bg-black" },
    { id: 16, text: "NONE", color: "bg-black" },
    { id: 17, text: "1000 XPOINTS", color: "bg-red" },
    { id: 18, text: "NONE", color: "bg-black" },
    { id: 19, text: "5 USDT", color: "bg-blue" },
    { id: 20, text: "NONE", color: "bg-black" },
    { id: 21, text: "NONE", color: "bg-black" },
    { id: 22, text: "5 XTICKET", color: "bg-purple" },
    { id: 23, text: "NONE", color: "bg-black" },
    { id: 24, text: "NFT GOLD", color: "bg-yellow" },
    // { id: 7, text: "Prize 7", color: "bg-pink" },
  ];